let numberLimit = 10;
// creates an empty list
let listOfSortedNumbers = [];
// variable that stores the random number generated by the function
let secretNumber = generateRandomNumber();
let attempts = 1;
let restartButton = document.querySelector("#restart");

// function that takes two parameters: a HTML tag (querySelector) and displays text in it
function displayTextOnScreen(tag, text) {
  let field = document.querySelector(tag);
  field.innerHTML = text;

  if ("speechSynthesis" in window) {
    let utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = "en";
    utterance.rate = 1;
    window.speechSynthesis.speak(utterance);
  } else {
    console.log("Web Speech API is not supported in this browser.");
  }
}

function displayInitialMessage() {
  displayTextOnScreen("h1", "Game");
  displayTextOnScreen("p", "Enter a number from 1 to 10");
}

displayInitialMessage();

// gets input value and stores it in variable guess
// then compares guess with secret number
// calls function to show if the user got it right or wrong
function checkGuess() {
  let guess = document.querySelector("input").value;

  if (guess == secretNumber) {
    displayTextOnScreen("h1", "You got it right!");
    let attemptWord = attempts > 1 ? "Attempts" : "Attempt";
    let messageAttempts = `You discovered the secret number in ${attempts} ${attemptWord}!`;
    displayTextOnScreen("p", messageAttempts);
    restartButton.removeAttribute("disabled");
  } else {
    if (guess > secretNumber) {
      displayTextOnScreen("h1", "You got it wrong");
      displayTextOnScreen("p", "The secret number is lower");
    } else {
      displayTextOnScreen("p", "The secret number is higher");
    }
    attempts++;
    clearField();
  }
}

// function that returns a random number
function generateRandomNumber() {
  let chosenNumber = parseInt(Math.random() * numberLimit + 1);
  let listSize = listOfSortedNumbers.length;

  if (listSize == numberLimit) {
    listOfSortedNumbers = [];
  }

  if (listOfSortedNumbers.includes(chosenNumber)) {
    return generateRandomNumber();
  } else {
    listOfSortedNumbers.push(chosenNumber);
    console.log(listOfSortedNumbers);

    return chosenNumber;
  }
}

function clearField() {
  let guess = document.querySelector("input");
  guess.value = "";
}

function restartGame() {
  secretNumber = generateRandomNumber();
  clearField();
  attempts = 1;
  displayInitialMessage();
  restartButton.setAttribute("disabled", true);
}